version: 2

models:
  - name: tbl_cl_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('tbl_cl_customers')
              field: customer_id
      - name: order_status
        tests:
          - accepted_values:
              values:
                ["placed", "shipped", "completed", "returned", "return_pending"]
  - name: tbl_cl_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: tbl_cl_payments
    columns:
      - name: payment_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
  - name: dim_customer
    description: "Customer Table"
    columns:
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
          - unique
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: first_order
        description: "First Order date"
      - name: most_recent_order
        description: "The last (most recent) order date for the customer"
      - name: number_of_orders
        description: "Number of orders placed till now (including returned orders)"
      - name: customer_lifetime_value
        description: "The sum of all payments made by the customer (including returned orders)"
